name: yaru_icons
version: 2.1.0
homepage: https://github.com/ubuntu/yaru_icons.dart
description: Ubuntu Yaru Icon theme

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: YaruIcons
      fonts:
        - asset: assets/yaru_icons.ttf
    - family: YaruIcons20
      fonts:
        - asset: assets/yaru_icons20.ttf

dev_dependencies:
  flutter_lints: ^2.0.1
